# Generated by Django 5.1 on 2024-08-20 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_warnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_applications', to='project.user'),
        ),
    ]
