# Generated by Django 5.1 on 2024-08-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_applications_confirmed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='confirmed_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
