# Generated by Django 5.1 on 2024-08-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_applications_confirmed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
