# Generated by Django 5.1.1 on 2024-09-21 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.CharField(blank=True, null=True, verbose_name='KELISH VAQTI')),
                ('departure_time', models.CharField(blank=True, null=True, verbose_name='KETISH VAQTI')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.user', verbose_name='FOYDALANUVCHI')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Ish grafiklari',
                'db_table': 'schedule',
            },
        ),
    ]
