# Generated by Django 5.1.1 on 2024-09-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='arrival_time',
            field=models.CharField(blank=True, max_length=221, null=True, verbose_name='KELISH VAQTI'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='departure_time',
            field=models.CharField(blank=True, max_length=221, null=True, verbose_name='KETISH VAQTI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Active?'),
        ),
    ]
